// Control FLow => MENGENDALIKAN ALUR PERJALANAN PROGRAM.
// MISAL. JIKA ADA PEREMPATAN JALAN, CONTROL FLOW AKAN MEMBERIKAN LOGIKA
// SEHINGGA PROGRAM TAU HARUS MELANJUTKAN KE KANAN, KE KIRI, ATAU LURUS

